### ISSUE TITLE
Samsung Internet versions from GA report fails to match

### ISSUE THREAD

**Issue by johannesodland** [browserslist/browserslist-ga-export#23]
The [trailing decimal that is added to browser version](https://github.com/browserslist/browserslist-ga-export/blob/24b0c873332af78fe7eca45de5a749a158199615/index.js#L82) makes Samsung browsers fail to match correctly in [browserslist-ga/caniuse-parser.js](https://github.com/browserslist/browserslist-ga/blob/c9678a53fbb5efba333f9da6ec0aac2633245e25/src/caniuse-parser.js#L144).  

The padded browser version for Samsung Internet is '17.0.0' and will be returned as is because isNaN('17.0.0') is true.

**Comment by galvarez421** [comment]
@johannesodland Thank you for reporting this! It looks like this is the same issue reported by https://github.com/browserslist/browserslist-ga-export/pull/22. I will be reviewing that pull request presently and hopefully merging it in to the next release soon.

**Comment by johannesodland** [comment]
@galvarez421 It's the same issue. I missed it when searching for similar issues. Thanks for fixing. 🙏

**Comment by galvarez421** [comment]
No problem! The fix for this issue is now available in [v4.0.2](https://github.com/browserslist/browserslist-ga-export/releases/tag/v4.0.2) (also published to [npm](https://www.npmjs.com/package/browserslist-ga-export/v/4.0.2)), thanks to @hoox!
