### ISSUE TITLE
Empty browserlist export due to bad locale

### ISSUE THREAD

**Issue by roxanebellot** [browserslist/browserslist-ga-export#24]
Hey ! I ran into an issue, just putting this here in case it can help others !

I follow the README instructions, but was left with an export containing only two values : 0 and null, like this : 

```
  "android": {
    "3": 0,
    "4": null,
```

After some exploration, here was the thing : despite having changed my language (according to README instructions) the GA report was still in my language (FR) so with space as hundreds separator. 

I made a quick and dirty script to remove them, if this can help somebody in a hurry : 

```python
import re 
src_file = "myfile.csv"

with open(src_file, "r+") as f: 
    lines = f.readlines() 
    f.seek(0) 
    for line in lines: 
        *_, nb = line.split(',') 
        if len(_) == 5: 
            nb = nb.replace(" ", "") 
            line = ','.join([*_, nb]) 
        f.write(line) 
    f.truncate() 
```

Maybe in the future different locale could be handled by browserslist-ga-export ?

**Comment by galvarez421** [comment]
Hi @roxanebellot, thank you for reporting this issue and for sharing your workaround!

Per https://github.com/browserslist/browserslist-ga-export/issues/14#issuecomment-636014934, after you changed your user language setting, did you "clear cookies and re-login into your account to see the new language"? I think that may be necessary.

**Comment by galvarez421** [comment]
Closing due to lack of response

**Comment by roxanebellot** [comment]
My bad, I completely forgot ! 

Indeed, clearing cookies and re-logging was necessary, thank you for your time.
