### ISSUE TITLE
The "Mobile (Including Tablet)" Dimension is Deprecated in GA

### ISSUE THREAD

**Issue by DaveLak** [browserslist/browserslist-ga-export#3]
There is a good chance that this issue belongs in the upstream [browserslist/browserslist-ga
](https://github.com/browserslist/browserslist-ga) repo; if that is in fact the case I'll close this and open a new issue there.

That said, it appears the "Mobile (Including Tablet)" dimension required in the exported report is deprecated as indicated by the warning icon in the UI:

<img width="247" alt="Screen shot of GA deprecation icon" src="https://user-images.githubusercontent.com/17415134/46574492-3a843e00-c972-11e8-90c6-ea2118acb68a.png">

As well as a warning prompt on save that reads:

>The following dimensions are deprecated:
>Mobile (Including Tablet)
>Deprecated concepts will eventually be removed, which may invalidate your report. Do you want to proceed?

<img width="611" alt="Screen shot of GA Depreciation Modal" src="https://user-images.githubusercontent.com/17415134/46574514-7a4b2580-c972-11e8-8870-72d66ef656eb.png">

Unfortunately I am not familiar with the GA API myself and as a result had trouble finding more information about this depreciation so I don't have a suggested path forward. Regardless I thought it's worth it to start the discussion.

**Comment by SalimBensiali** [comment]
@galvarez421 any updates on this? Are the instructions on this repo still good?

**Comment by galvarez421** [comment]
@SalimBensiali Given the description of this tool as allowing "you to generate the same `browserslist-stats.json` that Browserslist-GA would generate for a Google Analytics view", I think it makes sense to wait until [browserslist/browserslist-ga](https://github.com/browserslist/browserslist-ga) is updated to account for the deprecated dimension (https://github.com/browserslist/browserslist-ga/issues/14), lest the use of different dimensions result in a different `browserslist-stats.json` being produced.

Given that Browserslist-GA is still using the deprecated dimension and that the dimension is still usable in Google Analytics, the instructions in this repo are still good for now.

**Comment by SalimBensiali** [comment]
Sounds good to me. Thanks for taking the time to clarify.

**Comment by ogonkov** [comment]
Using deviceCategory instead of isMobile is seems works good.
I'm also noticed that my report has space-separated pageview values.

After replacing invisible spaces (` (\d+)\n`)
And replacing `mobile` and `tablet` to `Yes`, and `desktop` to `No`

Generation of json data started works properly.

Before replacing spaces in pageviews report generates `null` instead of numbers.

**Comment by galvarez421** [comment]
Resolved by https://github.com/browserslist/browserslist-ga-export/commit/4eaecbdced38b88b1653a911658e62fd67942190 and released in https://github.com/browserslist/browserslist-ga-export/releases/tag/v2.0.0.
