### ISSUE TITLE
Publish to npm registry

### ISSUE THREAD

**Issue by galvarez421** [browserslist/browserslist-ga-export#4]

**Comment by ai** [comment]
Right now you have a wrong URL in https://github.com/browserslist/browserslist-ga-export#installation

**Comment by galvarez421** [comment]
I have updated the references to the repository in the README and `package.json`

**Comment by ai** [comment]
What is a reason for using GitHub version right now? (Just curious)

**Comment by galvarez421** [comment]
The only reason is that the code has not been published to npm registry yet.

**Comment by danez** [comment]
Could this please be done :)

**Comment by galvarez421** [comment]
Sure! Done :)

https://www.npmjs.com/package/browserslist-ga-export

Note that I have published v1.0.1. I don't think I can publish v1.0.0 since `"private"` property was set to `true` in `package.json` in v1.0.0.
